# Generated by Django 5.0.4 on 2024-04-23 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='can_be_sharde',
            new_name='can_be_shared',
        ),
    ]
