# Generated by Django 5.0.4 on 2024-04-24 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_remove_user_age_user_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(default=14),
            preserve_default=False,
        ),
    ]
