# Generated by Django 5.0.4 on 2024-04-25 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_user_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='can_be_contacted',
            field=models.BooleanField(default=False, verbose_name="J'autorise SoftDeskSupport à me contacter"),
        ),
    ]
