# Generated by Django 5.0.4 on 2024-05-20 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0007_alter_user_age"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="can_be_shared",
            new_name="can_data_be_shared",
        ),
    ]
